# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strut < Formula
  desc "Gemini CLI"
  homepage "https://github.com/postsa/strut/"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/postsa/strut/releases/download/v0.0.3/strut_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "f5681afa9a1f85ed1d10e460db0b147067ce6c32aec93040368270f150783883"

      def install
        bin.install "strut"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/postsa/strut/releases/download/v0.0.3/strut_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "696b57369e04e75188f6a91e3b411929dd2245ac93548e52dd87c6034ab91e82"

      def install
        bin.install "strut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/postsa/strut/releases/download/v0.0.3/strut_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "d8aa7471c12659253de6c6cd8533f7467fcb8243f4938d401b377741b52a5d26"

        def install
          bin.install "strut"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/postsa/strut/releases/download/v0.0.3/strut_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "f8890c73e722f254e0e3d73bc90d845c00761e2ae77c543b6cc04460c36f12af"

        def install
          bin.install "strut"
        end
      end
    end
  end
end
