# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strut < Formula
  desc "Gemini CLI"
  homepage ""
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/postsa/strut/releases/download/v0.0.2/strut_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "b1fd0bd1a8a776469a5efe5348c361944cbf3b5aefe7aee3906178f4be6eef80"

      def install
        bin.install "strut"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/postsa/strut/releases/download/v0.0.2/strut_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "6a471b4ce62e2668cc3c46452fed38d7d127764dcf3ec3c4c8392661d9f60505"

      def install
        bin.install "strut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/postsa/strut/releases/download/v0.0.2/strut_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "5cde9907c3dbacffa393b2d93f498b3ba3506c0e1f1a0efdb38973445b2e4546"

        def install
          bin.install "strut"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/postsa/strut/releases/download/v0.0.2/strut_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "709dd142f4ea01380eeb2cb7759031d3dc89b6ad69ed793a49062b02bc80a725"

        def install
          bin.install "strut"
        end
      end
    end
  end
end
